Update CalcBasicTest.java
RenzO102/CalculatorTest pull request #1
Opened 2022-09-21 13:22 UTC by RenzO102

2022-09-26 08:05 UTC, kurau requested changes

2022-09-26 08:05 UTC, kurau commented on CalculactorTest/src/main/java/ru/github/com/RenzO102/Calculator.java
> +
Относись внимательно к форматированию кода
Можешь посмотреть как пишется код в разных библиотеках, в том же junit
Чистота в программировании очень важна
Потому что ты записываешь мысли в виде кода
Это практически как сочинение

2022-09-26 08:05 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +
Вот это вот лишнее например

2022-09-26 08:05 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +        assertThat("dsdfsd", calc.minus(v3, v2), is(v1));
Важно что ты пишешь, любой текст тут должен нести какую-то цель
Вот этот dsdfsd лучше вообще не писать, чем писать
Попробуй тут сформулировать описание ошибки 
Оно должно всегда начинаться со слова Should/Должно(Должен и тд)

2022-09-26 08:05 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
Везде форматирование поправь плз

2022-09-26 08:05 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    public void testParametersum() {
Тестовый метод давай сразу будем учиться писать правильно
Начинается со слова should

2022-09-26 08:05 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +        assertThat(12 * 5, is(60));
Те тесты, которые без параметров вынеси в отдельный класс
Иначе у тебя сейчас для каждого парметра запускаются все тесты, даже те, которые от параметров не зависят
Это условия работы фреймворка

2022-09-26 08:05 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    private static java.util.Arrays Arrays;
Это зачем?

2022-09-26 08:05 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    public CalcBasicTest(int v1, int v2, int v3) {
А это точно надо?

2022-09-26 08:15 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    public void testParametersum() {
Что значит начинается со слова Sholud , ShouldTestParamater ? так получается?

2022-09-26 08:50 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    private static java.util.Arrays Arrays;
Это я создал свойства , где v1,v2 это параметры . v3 это результат , который ожидаем.

2022-09-26 08:51 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    public CalcBasicTest(int v1, int v2, int v3) {
18 строчка , это автоматически добавляется когда беру из документации. 20 автоматический собранный конструктор

2022-09-26 09:04 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +        assertThat("dsdfsd", calc.minus(v3, v2), is(v1));
Исправил

2022-09-26 09:04 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +
Убрал

2022-09-26 09:04 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
Сделал

2022-09-26 09:12 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +        assertThat(12 * 5, is(60));
сделал

2022-09-26 09:17 UTC, RenzO102 commented on CalculactorTest/src/main/java/ru/github/com/RenzO102/Calculator.java
> +
Хорошо , спасибо

2022-09-26 09:18 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    public void testParametersum() {
Исправил , хорошо

2022-09-28 08:03 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    public CalcBasicTest(int v1, int v2, int v3) {
Просто кажется конструктор тут не нужен
Тебе достаточно методов с аннотацией @Parameter

2022-09-28 08:09 UTC, kurau requested changes

2022-09-28 08:09 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    private static java.util.Arrays Arrays;
Попробуй удали

2022-09-28 08:09 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> -    public double result;
Тут ещё третий нужен параметр

2022-09-28 08:09 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +        assertThat("Should be a different amount", calc.sum(v1, v2), is(v3));
Понял
Тебе нужно убрать конструктор и вернуть @Parameter

2022-09-28 08:09 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcTest.java
> +        assertThat(3 - 2, is(1));
Комметарий нужен! Это прям обязательно

2022-09-28 08:09 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcTest.java
> +    public void testMultiplication() {
shouldMultiplyTwoDigit

2022-09-28 08:09 UTC, kurau commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcTest.java
> +    public void testMultiply() {
Аналогично, переименовать

2022-09-28 09:07 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> -    public double result;
Добавил

2022-09-28 09:10 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +    public CalcBasicTest(int v1, int v2, int v3) {
убрал все это , через аннотацию @Parameterized.Parameter , все сделал , все работает

2022-09-28 09:10 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcBasicTest.java
> +        assertThat("Should be a different amount", calc.sum(v1, v2), is(v3));
Сделал , все рабоатает

2022-09-28 09:14 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcTest.java
> +        assertThat(3 - 2, is(1));
Сделал , глупая ошибка

2022-09-28 09:14 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcTest.java
> +    public void testMultiplication() {
Выполнил\

2022-09-28 09:14 UTC, RenzO102 commented on CalculactorTest/src/test/java/ru/github/com/RenzO102/CalcTest.java
> +    public void testMultiply() {
сделано

2023-09-25 14:27 UTC, merged